name: CI

on:
  pull_request:
  push:

jobs:   
  gcc8-build:
    name: GCC8 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
        os: ["ubuntu-self-hosted"]
    runs-on: ${{ matrix.os }}
    env:
      CXX_COMPILER: "g++-8"
      C_COMPILER: "gcc-8"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      BOOST_ROOT: "C:/boost_1_75_0"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy,pytest numpy scipy pytest
      
      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh
        if: ${{ contains(matrix.os, 'ubuntu') }}

      - name: Install qulacs Python module
        run: python setup.py install
      
      - name: import benchmark_qulacs
        uses: actions/checkout@v2
        with:
          repository: 'qulacs/benchmark-qulacs'
          path: './benchmark_qulacs'
      
      - name: Run MultiThread Benchmark
        run: |
          unset OMP_NUM_THREADS
          unset MKL_NUM_THREADS
          unset MKL_DOMAIN_NUM_THREADS
          unset JULIA_NUM_THREADS
          pytest ./benchmark_qulacs/benchmark/multithread/qulacs/benchmarks.py --benchmark-save="data" --benchmark-sort=name --benchmark-min-rounds=5