name: CI

on:
  push:
  pull_request:

jobs:
  gcc8-build:
    name: GCC8 build
    strategy:
      matrix:
        python-version: ["3.7.5", "2.7.17"]
        os: ["macos-self-hosted"]
    runs-on: ${{ matrix.os }}
    env:
      CXX_COMPILER: "g++-8"
      C_COMPILER: "gcc-8"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy

      - name: Workaround for OpenMP link error on mac
        # In GitHub Actions virtual environment macos-10.15/20201115.1,
        # linking some functions from libgomp fails since the linker cannot find
        # some library files from gcc-8 installed via Homebrew.
        # The following command fixes this issue by (brew) re-linking files from gcc-8.
        # cf. https://stackoverflow.com/a/55500164
        run: brew link --overwrite gcc@8
        if: ${{ contains(matrix.os, 'macos') }}
      
      - name: Install Boost for macOS
        run: |
          brew install boost
          brew link boost
        if: ${{ contains(matrix.os, 'macos') }}

      - name: Install qulacs for macOS
        run: ./script/build_gcc.sh
        if: ${{ contains(matrix.os, 'macos') }}

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in macOS
        run: |
          cd ./build
          make test
          make pythontest
        if: ${{ contains(matrix.os, 'macos') }}

  wheel-build:
    name: Python wheel build
    needs: gcc8-build
    strategy:
      matrix:
        python-version: ["3.7.5"]
        os: ["macos-self-hosted"]
    runs-on: ${{ matrix.os }}
    env:
      CXX_COMPILER: "g++-8"
      C_COMPILER: "gcc-8"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      CIBW_TEST_COMMAND: "python {project}/python/test/test_qulacs.py"
      CIBW_TEST_REQUIRES: "numpy scipy"
      CIBW_BEFORE_BUILD: "pip install cmake"
      # In GitHub Actions virtual environment macos-10.15/20201115.1,
      # linking some functions from libgomp fails since the linker cannot find
      # some library files from gcc-8 installed via Homebrew.
      # The following command fixes this issue by (brew) re-linking files from gcc-8.
      # cf. https://stackoverflow.com/a/55500164
      CIBW_BEFORE_BUILD_MACOS: "brew link --overwrite gcc@8 && pip install cmake && brew install boost && brew link boost"
      CIBW_BUILD: "cp*-macosx_x86_64 cp*-manylinux_x86_64 cp*-win_amd64"
      CIBW_BUILD_VERBOSITY: "1"
      CIBW_ENVIRONMENT: 'QULACS_OPT_FLAGS="-mtune=haswell -mfpmath=both"'
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && script/fix_wheel_osx.sh {wheel} {dest_dir} && delocate-listdeps {wheel}"
      TWINE_USERNAME: "__token__"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: python -m pip install cibuildwheel twine

      - name: Run cibuildwheel
        run: python -m cibuildwheel --output-dir wheels
        
      - name: Upload wheel data if the Git tag is set
        run: python -m twine upload wheels/*.whl
        if: ${{ contains(github.ref, '/tags/') }}
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_QULACS }}
