name: Ubuntu CI

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  gcc8-build:
    name: GCC8 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-20.04"
    env:
      CXX_COMPILER: "/usr/lib/ccache/g++"
      C_COMPILER: "/usr/lib/ccache/gcc"
      QULACS_OPT_FLAGS: "-mtune=haswell -march=haswell -mfpmath=both"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      CACHE_NAME: ccache-qulacs-build-v2
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install ccache
        run: sudo apt install ccache

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion mypy pybind11-stubgen

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Check stubs
        run: |
          ./script/update_stubs.sh
          diff=$(git diff)
          echo -n "$diff"
          # Without `-n`, `echo -n "$diff" | wc -l` is 1 even if `"$diff" is empty.`
          test $(echo -n "$diff" | wc -l) -eq 0

      - name: Test if stub is working
        run: |
          python python/stub-test/generate_mypy_tester.py qulacs_osaka
          python python/stub-test/generate_mypy_tester.py qulacs
          mypy python/stub-test/names_qulacs_osaka.py python/stub-test/names_qulacs.py

      - name: Test in Ubuntu
        run: |
          cd ./build
          make test
          make pythontest

      - name: Show cache stats
        run: ccache -s

  nvcc-gcc8-GPUbuild:
    name: nvcc + gcc8 build
    runs-on: "ubuntu-20.04"
    env:
      CXX_COMPILER: "/usr/lib/ccache/g++"
      C_COMPILER: "/usr/lib/ccache/gcc"
      QULACS_OPT_FLAGS: "-mtune=haswell -march=haswell -mfpmath=both"
      PYTHON: "3.7.5"
      COVERAGE: "ON"
      CACHE_NAME: ccache-qulacs-gpu-build-v2
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.5"
          architecture: x64

      - name: Install ccache
        run: sudo apt install ccache

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Install CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc_with_gpu.sh

      - name: Install qulacs Python module
        run: USE_GPU=Yes python setup.py install

      # Testing is removed because GPU is not available for GitHub-Hosted Runner.

  format:
    name: Format with clang-format
    runs-on: "ubuntu-20.04"
    container:
      image: ghcr.io/qulacs-osaka/qulacs-ubuntu-clang-format:latest
    steps:
      # This job is running on a docker container.
      # We can't use actions/checkout because Node.js is not installed on the container.
      # Therefore, we use `git clone` instead of actions/checkout.
      - name: clone /qulacs-osaka (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          # We use $REPOSITORY to support PR from the forked repository of Qulacs-Osaka/qulacs-osaka.
          REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          cd /
          git clone -b "${GITHUB_HEAD_REF#refs/*/}" https://github.com/$REPOSITORY

      - name: clone /qulacs-osaka (push) testing
        if: ${{ github.event_name == 'push' }}
        run: |
          cd /
          git clone -b "${GITHUB_REF#refs/*/}" https://github.com/${GITHUB_REPOSITORY}

      - name: format
        run: qulacs_format

      - name: Compare diff
        run: |
          cd /qulacs-osaka
          diff=$(git diff)
          echo -n "$diff"
          # Without `-n`, `echo -n "$diff" | wc -l` is 1 even if `"$diff" is empty.`
          test $(echo -n "$diff" | wc -l) -eq 0
